title: "[Question]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Ask questions about using MCP Toolkit!
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help us answer
      placeholder: I'm trying to...
