/**
 * Templates Resource
 *
 * Provides access to code generation templates via MCP resource templates.
 */

import type { ReadResourceResult, ResourceTemplate } from "@modelcontextprotocol/sdk/types.js";

/**
 * Resource template for code templates
 */
export const templatesResourceTemplate: ResourceTemplate = {
  uriTemplate: "toolkit://templates/{type}",
  name: "Code Templates",
  description: "Code generation templates for tools, resources, prompts, and handlers",
  mimeType: "text/plain",
};

/**
 * Available template types
 */
const templates: Record<string, string> = {
  tool: `/**
 * {{entityName}} Tool
 *
 * Tool definition for managing {{entityName}} entities.
 * Generated by MCP Toolkit
 */

import type { Tool } from "@modelcontextprotocol/sdk/types.js";

export const {{camelName}}Tool: Tool = {
  name: "{{kebabName}}:{{entityKebab}}",
  description: "{{description}}",
  inputSchema: {
    type: "object",
    properties: {
      action: {
        type: "string",
        enum: ["create", "read", "update", "delete", "list"],
        description: "CRUD action to perform",
      },
      id: {
        type: "string",
        description: "Entity ID (required for read, update, delete)",
      },
      data: {
        type: "object",
        description: "Entity data (required for create, update)",
      },
    },
    required: ["action"],
  },
};
`,

  resource: `/**
 * {{entityName}} Resource
 *
 * Resource template for {{entityName}} entities.
 * Generated by MCP Toolkit
 */

import type { ResourceTemplate } from "@modelcontextprotocol/sdk/types.js";

export const {{camelName}}Template: ResourceTemplate = {
  uriTemplate: "{{kebabName}}://{{entityKebab}}/{id}",
  name: "{{entityName}}",
  description: "{{description}}",
  mimeType: "application/json",
};
`,

  prompt: `/**
 * {{entityName}} Prompt
 *
 * Prompt definition for {{entityName}} assistance.
 * Generated by MCP Toolkit
 */

import type { Prompt } from "@modelcontextprotocol/sdk/types.js";

export const {{camelName}}Prompt: Prompt = {
  name: "{{kebabName}}-{{entityKebab}}-help",
  description: "Get help with {{entityName}} operations",
  arguments: [
    {
      name: "operation",
      description: "The operation you need help with",
      required: false,
    },
  ],
};
`,

  handler: `/**
 * {{entityName}} Handler
 *
 * Implementation for {{entityName}} CRUD operations.
 * Generated by MCP Toolkit
 */

import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";

export interface {{entityName}} {
  id: string;
  // Add your entity properties here
  createdAt: string;
  updatedAt: string;
}

export async function handle{{entityName}}(
  action: string,
  id: string | undefined,
  data: Partial<{{entityName}}> | undefined
): Promise<CallToolResult> {
  switch (action) {
    case "create":
      // TODO: Implement create
      return { content: [{ type: "text", text: "Created" }] };

    case "read":
      // TODO: Implement read
      return { content: [{ type: "text", text: "Read" }] };

    case "update":
      // TODO: Implement update
      return { content: [{ type: "text", text: "Updated" }] };

    case "delete":
      // TODO: Implement delete
      return { content: [{ type: "text", text: "Deleted" }] };

    case "list":
      // TODO: Implement list
      return { content: [{ type: "text", text: "Listed" }] };

    default:
      return {
        content: [{ type: "text", text: \`Unknown action: \${action}\` }],
        isError: true,
      };
  }
}
`,
};

/**
 * Read a template resource
 */
export async function readTemplateResource(type: string): Promise<ReadResourceResult | null> {
  const template = templates[type];

  if (!template) {
    return null;
  }

  return {
    contents: [
      {
        uri: `toolkit://templates/${type}`,
        mimeType: "text/plain",
        text: template,
      },
    ],
  };
}

/**
 * Get available template types
 */
export function getTemplateTypes(): string[] {
  return Object.keys(templates);
}
